// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_pos/models/cart_item.dart';
import 'package:flutter_pos/models/company_info.dart';
import 'package:flutter_pos/models/employee.dart';
import 'package:flutter_pos/models/payment_method.dart';
import 'package:flutter_pos/models/product.dart';
import 'package:flutter_pos/models/product_category.dart';
import 'package:flutter_pos/models/sale.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemAdapter());
    registerAdapter(CompanyInfoAdapter());
    registerAdapter(EmployeeAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductCategoryAdapter());
    registerAdapter(SaleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemAdapter());
    registerAdapter(CompanyInfoAdapter());
    registerAdapter(EmployeeAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductCategoryAdapter());
    registerAdapter(SaleAdapter());
  }
}
